name: Initialize Repository

on:
  push:
    branches: [ main ]
    # 确保只在仓库首次创建时运行
    paths:
      - '.github/workflows/initialize.yml'

jobs:
  initialize:
    runs-on: ubuntu-latest
    if: github.run_number == 1  # 尝试只在第一次运行时执行
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update README with repository name
        run: |
          # 获取仓库名称
          REPO_NAME=$(echo ${{ github.repository }} | awk -F/ '{print $2}')
          # 替换 README.md 中的项目名称 (假设有一个占位符 YOUR_PROJECT_NAME)
          sed -i "s/YOUR_PROJECT_NAME/$REPO_NAME/g" README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Initialize repository with actual project name" || echo "No changes to commit"
          git push